#!/bin/bash
### ============================================================
### LSF Batch Script — DAS Project GPU Pipeline
### Submit with:  bsub < batch/pipeline.sh
### ============================================================

#BSUB -J DASPipeline
#BSUB -q gpuv100
#BSUB -gpu "num=1:mode=exclusive_process"
#BSUB -n 4
#BSUB -R "rusage[mem=16GB]"
#BSUB -R "span[hosts=1]"
#BSUB -W 12:00
#BSUB -o /work3/s214374/DASProject/DASProject/logs/pipeline.out
#BSUB -e /work3/s214374/DASProject/DASProject/logs/pipeline.err

### --- Environment Setup ---
module load cuda/12.4.1
module load python3/3.11.11

### --- Navigate to project root ---
cd /work3/s214374/DASProject/DASProject

### --- Activate virtual environment ---
source .venv/bin/activate

### --- Disable Python output buffering (enables real-time monitoring) ---
export PYTHONUNBUFFERED=1

### --- Clear previous log files so each run looks fresh ---
> /work3/s214374/DASProject/DASProject/logs/pipeline.out
> /work3/s214374/DASProject/DASProject/logs/pipeline.err

### --- Confirm GPU is visible ---
echo "=== GPU Info ==="
nvidia-smi
python3 -c "import torch; print(f'PyTorch {torch.__version__}'); print(f'CUDA available: {torch.cuda.is_available()}'); print(f'Device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"CPU\"}')"

### --- Create output directories ---
mkdir -p logs data/reconstructions reports/figures models

### --- Run the full pipeline ---
echo "=== Starting Pipeline ==="s
python3 tasks.py
echo "=== Pipeline Complete ==="

### --- Metadata Info ---
echo "Metadata for this run is stored in: data/das_metadata.json (auto-generated by the pipeline)"
